---
services:
  traefik:
    container_name: traefik
    image: traefik
    pull_policy: always
    restart: always
    command:
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.ssh.address=:22
      - --entryPoints.websecure.address=:443
    ports:
      - 22:22
      - 443:443
    volumes:
      - ${PWD}/traefik/dynamic:/etc/traefik/dynamic
      - ${PWD}/certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    pull_policy: always
    restart: always
    labels:
      - traefik.http.services.gitlabweb.loadbalancer.server.port=80
      - traefik.http.routers.gitlabweb.service=gitlabweb
      - traefik.http.routers.gitlabweb.rule=PathPrefix(`/gitlab`)
      - traefik.http.routers.gitlabweb.entrypoints=websecure
      - traefik.http.routers.gitlabweb.tls=true

      - traefik.tcp.services.gitlabssh.loadbalancer.server.port=22
      - traefik.tcp.routers.gitlabssh.service=gitlabssh
      - traefik.tcp.routers.gitlabssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitlabssh.entrypoints=ssh
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${HOSTNAME?}/gitlab"
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'

  runner:
    container_name: runner
    image: gitlab/gitlab-runner
    pull_policy: always
    restart: always
    volumes:
      - gitlab_runner:/etc/gitlab-runner
      - ${PWD}/certs/ca.crt:/etc/gitlab-runner/certs/ca.crt
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    pull_policy: always
    restart: always
    labels:
      - traefik.http.services.nexus.loadbalancer.server.port=8081
      - traefik.http.routers.nexus.service=nexus
      - traefik.http.routers.nexus.rule=PathPrefix(`/nexus`)
      - traefik.http.routers.nexus.entrypoints=websecure
      - traefik.http.routers.nexus.tls=true
    environment:
      NEXUS_CONTEXT: nexus
      REGISTRY_HTTP_RELATIVEURLS: true
    volumes:
      - nexus:/nexus-data

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner:
  nexus:
